reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
force_multiline_blocks = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_modules = true
