name: Rust CI (nightly + benches)

on:
  push:
    branches: ["**"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build & Test • ${{ matrix.os }} • nightly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, clippy
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-registry-
      - uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-nightly-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-target-nightly-
      - run: cargo build --workspace --all-features --verbose
      - run: cargo test  --workspace --all-features --verbose

  bench:
    name: Benchmarks
    if: >
      contains(github.ref, 'refs/heads/feature/bencher') ||
      (github.event_name == 'pull_request' &&
       github.base_ref == 'feature/bencher')
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - uses: bencherdev/bencher@main   # :contentReference[oaicite:1]{index=1}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-registry-

      - name: Run Criterion benches and push to Bencher
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          bencher run \
            --adapter rust_criterion \
            --branch "$BRANCH" \
            --testbed ci-github-ubuntu-latest \
            --project "extended-float" \
            --github-actions "${{ secrets.GITHUB_TOKEN }}" \
            --err \
            "cargo bench"
